### ISSUE TITLE
Error on CMake : Cannot find source file: PrimeHack/Mods/EmuVariableManager.cpp

### ISSUE THREAD

**Issue by Linskun** [shiiion/Ishiiruka#13]
Error on CMake

```
CMake Error at Source/Core/Core/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    PrimeHack/Mods/EmuVariableManager.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc


CMake Error at Source/Core/Core/CMakeLists.txt:1 (add_library):
  No SOURCES given to target: core
```

Do you mean : 
./Source/Core/Core/PrimeHack/EmuVariableManager.cpp

?

**Comment by SirMangler** [comment]
Please verify you have cloned the repository correctly. The file is very much there in the correct location.

CMakeLists:
https://github.com/shiiion/Ishiiruka/blob/master/Source/Core/Core/CMakeLists.txt#L242

EmuVariableManager:
https://github.com/shiiion/Ishiiruka/blob/master/Source/Core/Core/PrimeHack/EmuVariableManager.cpp

**Comment by Linskun** [comment]
Yep, but it check on path : 
PrimeHack/Mods/EmuVariableManager.cpp

But the file is on :
PrimeHack/EmuVariableManager.cpp

Not on Mods subfolder

[EDIT]
Tried to change from :
```
  PrimeHack/Mods/ViewModifier.cpp
  PrimeHack/Mods/EmuVariableManager.cpp
  PrimeHack/HackConfig.cpp
```

to
```
  PrimeHack/Mods/ViewModifier.cpp
  PrimeHack/EmuVariableManager.cpp
  PrimeHack/HackConfig.cpp
```
on Source/Core/Core/CMakeLists.txt

and the CMake write correctly the build files

**Comment by SirMangler** [comment]
My bad. Tiredness blinded me. I stared at that file for an embarrassingly long time without realising the mistake. Thanks for pointing it out.

https://github.com/shiiion/Ishiiruka/commit/2166cee524c5907dbf1264bd0cdd9c40fe207588
